name: Consigliere
favicon: null
layout_spectrum: 0.9900454392191023
typography_spectrum: 0.9602107452228665
title: Consigliere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#474747'
    - '#6d6d6d'
    - '#b7b7b7'
  brandStrength: 0.1875
  lightness: 0.13580579520203173
  saturation: 0.561128247063607
  rhythmicContrast: 0.5062187814619392
purpose: []
