name: Consigliere
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94163
title: Consigliere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#709fb1'
    - '#fef7e7'
    - '#07080a'
    - '#e4b678'
    - '#955d3c'
  brandStrength: 0.1875
  lightness: 0.13580579520203173
  saturation: 0.561128247063607
  rhythmicContrast: 0.5062187814619392
purpose: []
